/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    groups: Group;
    books: Book;
    projects: Project;
    demos: Demo;
    pages: Page;
    media: Media;
    subscribers: Subscriber;
    'social-posts': SocialPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    demos: DemosSelect<false> | DemosSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate: string;
  /**
   * Whether this post has been sent to newsletter subscribers
   */
  newsletterSent?: boolean | null;
  scheduledPublishDate?: string | null;
  /**
   * Group/series slug (e.g. "the-singularity-log")
   */
  group?: string | null;
  /**
   * Order within group (lower = first)
   */
  order?: number | null;
  author?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional heading for inline newsletter CTA on this post
   */
  newsletterHeading?: string | null;
  /**
   * Optional description for inline newsletter CTA on this post
   */
  newsletterDescription?: string | null;
  /**
   * Workflow status for newsletter pipeline.
   */
  publish_status?: ('draft' | 'scheduled' | 'published' | 'sent') | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  key: string;
  title: string;
  description: string;
  coverImage?: string | null;
  buyLink?: string | null;
  hasBuyButton?: boolean | null;
  hasPreview?: boolean | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Stable project URL slug.
   */
  slug: string;
  title: string;
  description: string;
  image?: string | null;
  /**
   * Feature this project in the main navigation panel.
   */
  featured?: boolean | null;
  category?: ('fiction' | 'tools' | 'experiments' | 'audio-video' | 'community') | null;
  status?: ('active' | 'available' | 'in-progress' | 'archived') | null;
  href: string;
  external?: boolean | null;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  primaryCTA?: {
    label?: string | null;
    href?: string | null;
    type?: ('preview' | 'buy' | 'experiment' | 'youtube' | 'audio' | 'repo' | 'download' | 'other') | null;
  };
  resources?:
    | {
        label: string;
        href: string;
        kind: 'post' | 'preview' | 'buy' | 'youtube' | 'audio' | 'experiment' | 'repo' | 'download' | 'other';
        description?: string | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Blog post slugs to surface on the project hub page.
   */
  relatedPostSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos".
 */
export interface Demo {
  id: number;
  slug: string;
  title: string;
  description: string;
  image?: string | null;
  embedUrl: string;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Short description for search and social cards.
   */
  excerpt?: string | null;
  /**
   * Label shown above the intro box (e.g. "A note before we begin:")
   */
  intro_label?: string | null;
  /**
   * Optional intro box shown before main content.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional closing section shown after main content.
   */
  outro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Attribution line shown at the bottom of the outro box (e.g. "Kai, content writer for the Arcades")
   */
  byline?: string | null;
  /**
   * Footer copy (e.g. copyright notice)
   */
  footer_text?: string | null;
  footer_link_label?: string | null;
  footer_link_href?: string | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  tags?:
    | {
        tag: 'fiction' | 'tech' | 'updates';
        id?: string | null;
      }[]
    | null;
  subscribedAt?: string | null;
  unsubscribed?: boolean | null;
  unsubscribedAt?: string | null;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  platform: 'bluesky';
  variant: 'short' | 'long' | 'custom';
  text: string;
  /**
   * Blog post slug this social post promotes (optional)
   */
  slug?: string | null;
  linkUrl?: string | null;
  status: 'scheduled' | 'posted' | 'cancelled' | 'failed';
  scheduledAt?: string | null;
  postedAt?: string | null;
  cancelledAt?: string | null;
  failedAt?: string | null;
  failureReason?: string | null;
  /**
   * AT Protocol URI
   */
  postUri?: string | null;
  /**
   * Web URL to live post
   */
  postUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'demos';
        value: number | Demo;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  newsletterSent?: T;
  scheduledPublishDate?: T;
  group?: T;
  order?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterDescription?: T;
  publish_status?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  buyLink?: T;
  hasBuyButton?: T;
  hasPreview?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  image?: T;
  featured?: T;
  category?: T;
  status?: T;
  href?: T;
  external?: T;
  tags?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        href?: T;
        kind?: T;
        description?: T;
        external?: T;
        id?: T;
      };
  relatedPostSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos_select".
 */
export interface DemosSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  image?: T;
  embedUrl?: T;
  tags?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  intro_label?: T;
  intro?: T;
  content?: T;
  outro?: T;
  byline?: T;
  footer_text?: T;
  footer_link_label?: T;
  footer_link_href?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  subscribedAt?: T;
  unsubscribed?: T;
  unsubscribedAt?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  platform?: T;
  variant?: T;
  text?: T;
  slug?: T;
  linkUrl?: T;
  status?: T;
  scheduledAt?: T;
  postedAt?: T;
  cancelledAt?: T;
  failedAt?: T;
  failureReason?: T;
  postUri?: T;
  postUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}