/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    'post-reactions': PostReaction;
    'postmark-events': PostmarkEvent;
    groups: Group;
    books: Book;
    demos: Demo;
    pages: Page;
    media: Media;
    'nav-items': NavItem;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-reactions': PostReactionsSelect<false> | PostReactionsSelect<true>;
    'postmark-events': PostmarkEventsSelect<false> | PostmarkEventsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    demos: DemosSelect<false> | DemosSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'nav-items': NavItemsSelect<false> | NavItemsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'publish-queue': PublishQueue;
  };
  globalsSelect: {
    'publish-queue': PublishQueueSelect<false> | PublishQueueSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date shown publicly and used for sorting published posts.
   */
  publishedDate: string;
  /**
   * When true, scheduled publishing will not send a per-post newsletter.
   */
  suppressNewsletter?: boolean | null;
  /**
   * Postmark newsletter delivery state. Read-only — written by the scheduled publish job.
   */
  newsletterSend?: {
    /**
     * Comma-separated Postmark message ids.
     */
    messageId?: string | null;
    status?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
    /**
     * Comma-separated ActiveCampaign list ids used to resolve recipients.
     */
    targetedLists?: string | null;
    /**
     * Number of deduplicated recipients resolved from ActiveCampaign.
     */
    recipientCount?: number | null;
    /**
     * Number of recipients accepted by Postmark.
     */
    acceptedCount?: number | null;
    /**
     * Number of recipient-level Postmark API failures on the latest send attempt.
     */
    failedCount?: number | null;
    /**
     * Number of accepted messages confirmed delivered by Postmark webhooks.
     */
    deliveredCount?: number | null;
    /**
     * Number of accepted messages that later bounced.
     */
    bouncedCount?: number | null;
    /**
     * Number of accepted messages with an open event when open tracking is enabled.
     */
    openedCount?: number | null;
    /**
     * Number of accepted messages with a click event when link tracking is enabled.
     */
    clickedCount?: number | null;
    /**
     * Number of accepted messages with a spam complaint.
     */
    complainedCount?: number | null;
    sentAt?: string | null;
    lastSyncedAt?: string | null;
    /**
     * Most recent Postmark event timestamp for this post.
     */
    lastEventAt?: string | null;
    /**
     * Most recent newsletter delivery error. Cleared on successful send.
     */
    lastError?: string | null;
  };
  /**
   * When a draft should be promoted to published by the scheduler.
   */
  scheduledPublishDate?: string | null;
  previewUrl?: string | null;
  /**
   * Group/series slug (e.g. "the-singularity-log")
   */
  group?: string | null;
  /**
   * Order within group (lower = first)
   */
  order?: number | null;
  /**
   * Chapter slug within the group (matches a chapter defined on the group)
   */
  chapter?: string | null;
  author?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional heading for inline newsletter CTA on this post
   */
  newsletterHeading?: string | null;
  /**
   * Optional description for inline newsletter CTA on this post
   */
  newsletterDescription?: string | null;
  /**
   * Internal scheduling/newsletter workflow. Payload draft/published state lives in Status.
   */
  publish_status?: ('draft' | 'scheduled' | 'published' | 'sent') | null;
  /**
   * Auto-generated. Stable across edits so shared preview links keep working.
   */
  previewToken?: string | null;
  /**
   * Show this published post on /samples.
   */
  showInSamples?: boolean | null;
  /**
   * Lower numbers appear first. Posts without a value fall back to publish date.
   */
  sampleOrder?: number | null;
  /**
   * Optional button text for /samples.
   */
  sampleLabel?: string | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Anonymous reader reactions on posts. One row per (post, emoji, clientId).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-reactions".
 */
export interface PostReaction {
  id: number;
  post: number | Post;
  emoji: string;
  clientId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Postmark delivery audit trail. Created from send responses and Postmark webhooks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postmark-events".
 */
export interface PostmarkEvent {
  id: number;
  /**
   * Resolved from Postmark metadata or the original submitted message.
   */
  post?: (number | null) | Post;
  messageId: string;
  eventType:
    | 'submitted'
    | 'delivery'
    | 'bounce'
    | 'open'
    | 'click'
    | 'spam_complaint'
    | 'subscription_change'
    | 'smtp_api_error'
    | 'other';
  /**
   * Recipient address from Postmark. Admin-only for support lookups.
   */
  recipientEmail?: string | null;
  /**
   * Postmark Tag value sent with the message or received in the webhook.
   */
  tag?: string | null;
  /**
   * Postmark message stream, e.g. broadcast or outbound.
   */
  messageStream?: string | null;
  occurredAt?: string | null;
  /**
   * Provider response text, bounce details, delivery details, or error message.
   */
  details?: string | null;
  /**
   * Custom Postmark metadata attached to the email.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Raw Postmark event payload for debugging.
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  title: string;
  /**
   * Stable group/project URL slug.
   */
  slug: string;
  description?: string | null;
  /**
   * Jacket-copy blurb shown on the intro page — a short, punchy pitch for the project.
   */
  jacketDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  href?: string | null;
  /**
   * Whether `href` points off-site.
   */
  external?: boolean | null;
  /**
   * Feature this group in the main navigation panel.
   */
  featured?: boolean | null;
  /**
   * Show this group in the "Current projects" section on the home page.
   */
  homeHighlight?: boolean | null;
  category?: ('fiction' | 'tools' | 'experiments' | 'audio-video' | 'community' | 'writing') | null;
  status?: ('active' | 'available' | 'in-progress' | 'archived') | null;
  /**
   * Serial: posts read in order (chapters). Collection: independent pieces (e.g. short stories) — the intro page shows a picker instead of a "Start reading" button.
   */
  format?: ('serial' | 'collection') | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary call-to-action for the project hub page.
   */
  projectCTA?: {
    label?: string | null;
    href?: string | null;
    type?: ('preview' | 'buy' | 'experiment' | 'youtube' | 'audio' | 'repo' | 'download' | 'other') | null;
  };
  resources?:
    | {
        label: string;
        href: string;
        kind: 'post' | 'preview' | 'buy' | 'youtube' | 'audio' | 'experiment' | 'repo' | 'download' | 'other';
        description?: string | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional chapter groupings. Posts can reference a chapter slug to appear under that section in the doc drawer.
   */
  chapters?:
    | {
        title: string;
        /**
         * Unique slug within this group, referenced by the post Chapter field.
         */
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Extra blog post slugs to surface beyond posts whose `group` field already matches this slug.
   */
  relatedPostSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  key: string;
  title: string;
  description: string;
  coverImage?: string | null;
  buyLink?: string | null;
  hasBuyButton?: boolean | null;
  hasPreview?: boolean | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos".
 */
export interface Demo {
  id: number;
  slug: string;
  title: string;
  description: string;
  image?: string | null;
  embedUrl: string;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Short description for search and social cards.
   */
  excerpt?: string | null;
  /**
   * Label shown above the intro box (e.g. "A note before we begin:")
   */
  intro_label?: string | null;
  /**
   * Optional intro box shown before main content.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional closing section shown after main content.
   */
  outro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Attribution line shown at the bottom of the outro box (e.g. "Kai, content writer for the Arcades")
   */
  byline?: string | null;
  /**
   * Footer copy (e.g. copyright notice)
   */
  footer_text?: string | null;
  footer_link_label?: string | null;
  footer_link_href?: string | null;
  /**
   * Controls how this content is surfaced and distributed.
   */
  discoverability?: {
    /**
     * One-liner for social sharing (Bluesky, etc.)
     */
    social_hook?: string | null;
    /**
     * Short summary for search and AI indexing.
     */
    search_summary?: string | null;
    /**
     * Canonical URL path (e.g. /about)
     */
    canonical_path?: string | null;
    /**
     * Include on the Start Here page.
     */
    featured_on_start_here?: boolean | null;
    primaryCTA?: {
      label?: string | null;
      href?: string | null;
      description?: string | null;
    };
  };
  meta?: {
    /**
     * Override the <title>. Defaults to the document title.
     */
    title?: string | null;
    /**
     * Meta description for SEO.
     */
    description?: string | null;
    /**
     * OG image for social sharing.
     */
    image?: (number | null) | Media;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Navigation bar items — control label, route, order, visibility, and which item gets the primary (highlighted) treatment.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items".
 */
export interface NavItem {
  id: number;
  label: string;
  /**
   * Route or URL (e.g. /projects or https://store.example.com)
   */
  href: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Uncheck to hide this item without deleting it.
   */
  visible?: boolean | null;
  /**
   * Gives this item the highlighted (glowing border) primary treatment.
   */
  isPrimary?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-reactions';
        value: number | PostReaction;
      } | null)
    | ({
        relationTo: 'postmark-events';
        value: number | PostmarkEvent;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'demos';
        value: number | Demo;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'nav-items';
        value: number | NavItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  suppressNewsletter?: T;
  newsletterSend?:
    | T
    | {
        messageId?: T;
        status?: T;
        targetedLists?: T;
        recipientCount?: T;
        acceptedCount?: T;
        failedCount?: T;
        deliveredCount?: T;
        bouncedCount?: T;
        openedCount?: T;
        clickedCount?: T;
        complainedCount?: T;
        sentAt?: T;
        lastSyncedAt?: T;
        lastEventAt?: T;
        lastError?: T;
      };
  scheduledPublishDate?: T;
  previewUrl?: T;
  group?: T;
  order?: T;
  chapter?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterDescription?: T;
  publish_status?: T;
  previewToken?: T;
  showInSamples?: T;
  sampleOrder?: T;
  sampleLabel?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-reactions_select".
 */
export interface PostReactionsSelect<T extends boolean = true> {
  post?: T;
  emoji?: T;
  clientId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postmark-events_select".
 */
export interface PostmarkEventsSelect<T extends boolean = true> {
  post?: T;
  messageId?: T;
  eventType?: T;
  recipientEmail?: T;
  tag?: T;
  messageStream?: T;
  occurredAt?: T;
  details?: T;
  metadata?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  jacketDescription?: T;
  image?: T;
  href?: T;
  external?: T;
  featured?: T;
  homeHighlight?: T;
  category?: T;
  status?: T;
  format?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  projectCTA?:
    | T
    | {
        label?: T;
        href?: T;
        type?: T;
      };
  resources?:
    | T
    | {
        label?: T;
        href?: T;
        kind?: T;
        description?: T;
        external?: T;
        id?: T;
      };
  chapters?:
    | T
    | {
        title?: T;
        slug?: T;
        id?: T;
      };
  relatedPostSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  key?: T;
  title?: T;
  description?: T;
  coverImage?: T;
  buyLink?: T;
  hasBuyButton?: T;
  hasPreview?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demos_select".
 */
export interface DemosSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  image?: T;
  embedUrl?: T;
  tags?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  intro_label?: T;
  intro?: T;
  content?: T;
  outro?: T;
  byline?: T;
  footer_text?: T;
  footer_link_label?: T;
  footer_link_href?: T;
  discoverability?:
    | T
    | {
        social_hook?: T;
        search_summary?: T;
        canonical_path?: T;
        featured_on_start_here?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-items_select".
 */
export interface NavItemsSelect<T extends boolean = true> {
  label?: T;
  href?: T;
  order?: T;
  visible?: T;
  isPrimary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-queue".
 */
export interface PublishQueue {
  id: number;
  fictionQueue?:
    | {
        post: number | Post;
        id?: string | null;
      }[]
    | null;
  essaysQueue?:
    | {
        post: number | Post;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publish-queue_select".
 */
export interface PublishQueueSelect<T extends boolean = true> {
  fictionQueue?:
    | T
    | {
        post?: T;
        id?: T;
      };
  essaysQueue?:
    | T
    | {
        post?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  /**
   * YouTube video id (the 11-char string after v= or youtu.be/). Pasting a full URL also works.
   */
  videoId: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}